### ISSUE TITLE
mqtt.createClient is not a function

### ISSUE THREAD

**Issue by fspasovski** [denschu/mqtt-exec#5]
Hello,
When executing the command:  
`mqtt-exec -c /usr/lib/node_modules/mqtt-exec/config-example.json -h mqtt://localhost:1883`
I get the next error on the line bellow: 
/usr/lib/node_modules/mqtt-exec/mqtt-exec.js:49
var c = mqtt.createClient(mqtt_url.port, mqtt_url.hostname, {
         

```
TypeError: mqtt.createClient is not a function
    at Object.<anonymous> (/usr/lib/node_modules/mqtt-exec/mqtt-exec.js:49:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

```
Do you have any idea what's the problem?

**Comment by SIM0N-F** [comment]
Hi, I have same problem on my debian 9.6 @fspasovski you have solved this issue ?

This by advance.

**Comment by twistedcustomdevel** [comment]
npm remove mqtt
npm install mqtt@1.0.0

mqtt.createClient is outdated as of mqtt.js 2.0.0. Current version is 4.0.0. The only way to fix this is to update mqtt-exec.js to reflect the methods available in 4.0.0. Downgrading as suggested above is not advised but it is a functional temporary solution.

**Comment by Xavelyn** [comment]
If somebody is interested in my solution for this problem: [https://pastebin.com/kv9Nc5zW](url)
Just copy the code from the link and replace it into /usr/local/lib/node_modules/mqtt-exec/mqtt-exec.js

**Comment by thiagolcordeiro** [comment]
> 
Hello @Xavelyn 
this link if off?
